### ISSUE TITLE
Performing apple attestation some times throws a python exception

### ISSUE THREAD

**Issue by jleach** [bcgov/bc-wallet-mobile#1899]
During the apple attestation process there seem to be some string format errors. These should be corrected so that they do not throw exceptions. They are probably doing string substitution on a data type that is not properly being marshalled into a string.

```log
INFO:controller:Run POST /topic/drpc_response/
INFO:controller:handle_attestation_challenge
INFO:controller:testing apple challenge
INFO:apple:Decoding attestation object...
INFO:apple:Apple Attestation step 1...
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/local/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 236, in run
    super().run()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 202, in run
    self.manage_workers()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 571, in manage_workers
    self.spawn_workers()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 642, in spawn_workers
    self.spawn_worker()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 142, in init_process
    self.run()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 126, in run
    self.run_for_one(timeout)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 70, in run_for_one
    self.accept(listener)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 32, in accept
    self.handle(listener, client, addr)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 178, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/opt/controller/controller.py", line 191, in drpc_response
    handle_drpc_challenge_response(resp, connection_id)
  File "/opt/controller/controller.py", line 127, in handle_drpc_challenge_response
    is_valid_challenge = verify_attestation_statement(
  File "/opt/controller/apple.py", line 210, in verify_attestation_statement
    verify_x5c_status = verify_x5c_certificates(apple_attestation_object)
  File "/opt/controller/apple.py", line 83, in verify_x5c_certificates
    logger.info("root_certificate", root_certificate.subject)
Message: 'root_certificate'
Arguments: (<Name(CN=Apple App Attestation Root CA,O=Apple Inc.,ST=California)>,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/local/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 236, in run
    super().run()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 202, in run
    self.manage_workers()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 571, in manage_workers
    self.spawn_workers()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 642, in spawn_workers
    self.spawn_worker()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 142, in init_process
    self.run()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 126, in run
    self.run_for_one(timeout)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 70, in run_for_one
    self.accept(listener)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 32, in accept
    self.handle(listener, client, addr)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 178, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/opt/controller/controller.py", line 191, in drpc_response
    handle_drpc_challenge_response(resp, connection_id)
  File "/opt/controller/controller.py", line 127, in handle_drpc_challenge_response
    is_valid_challenge = verify_attestation_statement(
  File "/opt/controller/apple.py", line 210, in verify_attestation_statement
    verify_x5c_status = verify_x5c_certificates(apple_attestation_object)
  File "/opt/controller/apple.py", line 84, in verify_x5c_certificates
    logger.info("credential_certificate", credential_certificate.subject)
Message: 'credential_certificate'
Arguments: (<Name(CN=c316a3ddbfee9ef821133a3c8ee4aa2f5990f4a990cdbe463e566a32981de9a3,OU=AAA Certification,O=Apple Inc.,ST=California)>,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/local/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 236, in run
    super().run()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 202, in run
    self.manage_workers()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 571, in manage_workers
    self.spawn_workers()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 642, in spawn_workers
    self.spawn_worker()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 142, in init_process
    self.run()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 126, in run
    self.run_for_one(timeout)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 70, in run_for_one
    self.accept(listener)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 32, in accept
    self.handle(listener, client, addr)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 178, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/opt/controller/controller.py", line 191, in drpc_response
    handle_drpc_challenge_response(resp, connection_id)
  File "/opt/controller/controller.py", line 127, in handle_drpc_challenge_response
    is_valid_challenge = verify_attestation_statement(
  File "/opt/controller/apple.py", line 210, in verify_attestation_statement
    verify_x5c_status = verify_x5c_certificates(apple_attestation_object)
  File "/opt/controller/apple.py", line 85, in verify_x5c_certificates
    logger.info("intermediate_certificate", intermediate_certificate.subject)
Message: 'intermediate_certificate'
Arguments: (<Name(CN=Apple App Attestation CA 1,O=Apple Inc.,ST=California)>,)
INFO:apple:The child certificate was issued by the parent certificate.
INFO:apple:The certificates are signed by the ROOT certificate.
INFO:apple:Apple Attestation step 2...
INFO:apple:Apple Attestation step 3...
INFO:apple:Apple Attestation step 4...
INFO:apple:Apple Attestation step 5...
INFO:apple:Apple Attestation step 6...
INFO:apple:Apple Attestation step 7...
INFO:apple:Apple Attestation step 8...
INFO:apple:Apple Attestation step 9...
INFO:apple:Successful apple attestation
INFO:controller:valid challenge
INFO:traction:issue_attestation_credential
INFO:traction:Sending offer to 86c47347-13ad-45c2-95b0-f037b102d4fc, offer = {'auto_issue': True, 'auto_remove': True, 'trace': True, 'cred_def_id': 'RycQpZ9b4NaXuT5ZGjXkUE:3:CL:120:bcwallet', 'credential_preview': {'@type': 'issue-credential/1.0/credential-preview', 'attributes': [{'name': 'operating_system', 'value': 'iOS'}, {'name': 'operating_system_version', 'value': '17.4.1'}, {'name': 'validation_method', 'value': 'apple:app-attest'}, {'name': 'app_id', 'value': 'ca.bc.gov.BCWallet'}, {'name': 'app_vendor', 'value': 'Government of British Columbia'}, {'name': 'issue_date_dateint', 'value': '20240402'}, {'name': 'app_version', 'value': '1.0.16-1636'}]}, 'comment': '', 'connection_id': '86c47347-13ad-45c2-95b0-f037b102d4fc'}
INFO:traction:Offer sent successfully
INFO:controller:Run GET /ping/
INFO:controller:Run GET /ping/
INFO:controller:Run GET /ping/
```

**Comment by jleach** [comment]
I think the problem is apple.py) L83-85. The `.subject` cannot be printed in logger.info the way it is. The subject property of a certificate in Python is an instance of the Name class, which is (I think) a sequence of NameAttribute objects. To print it properly, you can convert it to a string using the str() function.


```python
logger.info(f"root_certificate: {str(root_certificate.subject)}")
logger.info(f"credential_certificate: {str(credential_certificate.subject)}")
logger.info(f"intermediate_certificate {str(intermediate_certificate.subject)}")
```

**Comment by jleach** [comment]
Texted. Fix confirmed.
